### PR TITLE
Bug 2086921: Controller metrics not exposed/collected properly...

### PR DESCRIPTION
**Pull request by rauhersu**
Prometheus ServiceMonitor CR has been enabled by default

### CODE REVIEW

**Comment by jc-rh** [comment]
Running `make bundle` with this change modified the bundle docker file:
```
- LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.16.0-ocp
+ LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.10.1-ocp
```

**Comment by donpenney** [comment]
> 

@jc-rh I think most likely you have a stale bin/operator-sdk in your repo. The rule in the Makefile downloads the 1.16.0 version, but it only does an existence check. If you have an operator-sdk previously downloaded (4.10 branch had 1.10 version), it will satisfy the Makefile rule and you'll see what you're seeing. Delete the file and run "make operator-sdk" again, and you should see this resolved, I think

**Comment by jc-rh** [comment]
> > 
> 
> @jc-rh I think most likely you have a stale bin/operator-sdk in your repo. The rule in the Makefile downloads the 1.16.0 version, but it only does an existence check. If you have an operator-sdk previously downloaded (4.10 branch had 1.10 version), it will satisfy the Makefile rule and you'll see what you're seeing. Delete the file and run "make operator-sdk" again, and you should see this resolved, I think

Thanks. I just realized that.

**Comment by jc-rh** [comment]
@rauhersu Please run `make bundle` and check in the generated changes.

**Comment by rauhersu** [comment]
> @rauhersu Please run `make bundle` and check in the generated changes.

```
$ make bundle                                                                                                                                                                                  
/home/rauherna/gorepo/cluster-group-upgrades-operator/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:ar\
tifacts:config=config/crd/bases                                                                                                                                                                
/home/rauherna/gorepo/cluster-group-upgrades-operator/bin/operator-sdk generate kustomize manifests -q                                                                                         
cd config/manager && /home/rauherna/gorepo/cluster-group-upgrades-operator/bin/kustomize edit set image controller=quay.io/openshift-kni/cluster-group-upgrades-operator:4.11.0 && PRECACHE_IMG=quay.io/openshift-kni/cluster-group-upgrades-operator-precache:4.11.0 RECOVERY_IMG=quay.io/openshift-kni/cluster-group-upgrades-operator-recovery:4.11.0 envsubst < related-images/in.yaml >related-images/patch.yaml                                                                                                                                                                     
/home/rauherna/gorepo/cluster-group-upgrades-operator/bin/kustomize build config/manifests | /home/rauherna/gorepo/cluster-group-upgrades-operator/bin/operator-sdk generate bundle -q --overw\
rite --version 4.11.0                                                                                                                                                                          
INFO[0000] Creating bundle.Dockerfile                                                                                                                                                          
INFO[0000] Creating bundle/metadata/annotations.yaml                                                                                                                                           
INFO[0000] Bundle metadata generated suceessfully                                                                                                                                              
/home/rauherna/gorepo/cluster-group-upgrades-operator/bin/operator-sdk bundle validate ./bundle                                                                                                
INFO[0000] All validation tests have completed successfully 
```
The ServiceMonitor CR is now included under:

`bundle/manifests/cluster-group-upgrades-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml`

**Comment by rauhersu** [comment]
pinging @jc-rh @donpenney  for lgtm label

**Pull request merged**
