### PR TITLE
Add recovery image to bundle

### PR DESCRIPTION
**Pull request by danielmellado**
This commit adds the recovery image to the ClusterServiceVersion so is
shipped as a relatedImage for the operator.

Signed-off-by: Daniel Mellado <dmellado@redhat.com>

### CODE REVIEW

**Comment by danielmellado** [comment]
*NOTE*: To be put on hold until we get the recovery image into quay, based on either ubi or openshift golang builder. I'll follow up with other PR.

**Review by donpenney — APPROVED** [review]
/lgtm

**Review by donpenney — COMMENTED** [review]
/lgtm

**Pull request merged**
