### PR TITLE
OCPBUGS-18866: Set base CSV replaces field

### PR DESCRIPTION
**Pull request by sudomakeinstall2**

### CODE REVIEW

**Review by rauhersu — APPROVED** [review]

**Review by nishant-parekh — APPROVED** [review]

**Comment by nishant-parekh** [comment]
I think this branch needs a rebase @sudomakeinstall2

**Review by nishant-parekh — APPROVED** [review]
/lgtm
/approve

**Comment by nishant-parekh** [comment]
@sudomakeinstall2 @jc-rh do we need a go.sum update for just adding an annotation to the csv?

**Comment by jc-rh** [comment]
Replaced by #679

**Pull request closed without merging**
