### PR TITLE
OCPBUGS-3047: Avoid precaching subscriptions with mustnothave complianceType

### PR DESCRIPTION
**Pull request by sudomakeinstall2**
Signed-off-by: Saeid Askari <saskari@redhat.com>

### CODE REVIEW

**Comment by jc-rh** [comment]
Add some unit test? We have the platform case covered in validation_test.go

**Comment by sudomakeinstall2** [comment]
Unittest added
@jc-rh

**Review by jc-rh — APPROVED** [review]

**Pull request merged**
