### PR TITLE
Enhancement CNF-5013: Delete precaching objects on final cleanup

### PR DESCRIPTION
**Pull request by fontivan**
Makes the clean up more consistent

### CODE REVIEW

**Comment by jc-rh** [comment]
Why did we keep the existing call?

**Comment by sabbir-47** [comment]
> Why did we keep the existing call?

I think the initial idea was to clean the backup and/or precaching job and its related managedclusterView objects just before update the operator status on upgrade has been complete. In any case, have you verified with the delete resource actually does the delete of these jobs and objects as expected?

**Comment by fontivan** [comment]
> > Why did we keep the existing call?
> 
> I think the initial idea was to clean the backup and/or precaching job and its related managedclusterView objects just before update the operator status on upgrade has been complete. In any case, have you verified with the delete resource actually does the delete of these jobs and objects as expected?

I checked this today by performing an upgrade with backup enabled, watched the backup run, and can confirm there are no MCV objects present after it completes

**Pull request merged**
