### PR TITLE
Add go-bindata module dependency

### PR DESCRIPTION
**Pull request by donpenney**
The go-bindata package supports the generation of Go source code from
a static file. This mechanism is used by the upgrade recovery image to
build the recovery utility into the image for delivery to the spoke as
part of taking the pre-upgrade backup.

Signed-off-by: Don Penney <dpenney@redhat.com>

### CODE REVIEW

**Comment by danielmellado** [comment]
I assume you'll be landing a follow-up which will be using this dependency

**Comment by donpenney** [comment]
> 

Yes, I'm breaking down the integration work into multiple smaller PRs for easier review.

**Pull request merged**
