### PR TITLE
Remove the extra forced reconcile

### PR DESCRIPTION
**Pull request by jc-rh**
This fixes race conditions and reconcile errors when running the precaching with config test.

### CODE REVIEW

**Comment by irinamihai** [comment]
@jc-rh , how were the 2 force reconciles causing a race condition? :thinking:

**Comment by jc-rh** [comment]
> @jc-rh , how were the 2 force reconciles causing a race condition? thinking

The extra reconcile can happen while the next test step making changes to policies and CGU itself. So TALM was reconciling with part of the changes from the next step which messes up the precaching state machine. We end up going backwards from starting to preparing. And the log is full of this kind of error:

```
2023-07-25T16:06:05-04:00	ERROR	Reconciler error	{"controller": "clustergroupupgrade", "controllerGroup": "ran.openshift.io", "controllerKind": "ClusterGroupUpgrade", "ClusterGroupUpgrade": {"name":"cgu","namespace":"default"}, "namespace": "default", "name": "cgu", "reconcileID": "52ee6ca3-9a6e-4c79-a99a-1eae7d04e403", "error": "Operation cannot be fulfilled on clustergroupupgrades.ran.openshift.io \"cgu\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/jun/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/jun/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/jun/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
```

**Pull request merged**
