### PR TITLE
Add support for podman in catalog-build target

### PR DESCRIPTION
**Pull request by leo8a**
Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)

### CODE REVIEW

**Review by sudomakeinstall2 — APPROVED** [review]

**Comment by jc-rh** [comment]
Overriding as the actual test passed: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-kni_cluster-group-upgrades-operator/471/pull-ci-openshift-kni-cluster-group-upgrades-operator-main-integration/1626327882663989248

**Pull request merged**
