### PR TITLE
Fix linting issues for 1.19

### PR DESCRIPTION
**Pull request by sudomakeinstall2**
Signed-off-by: Saeid Askari <saskari@redhat.com>

### CODE REVIEW

**Comment by jc-rh** [comment]
@donpenney any idea why the verify bin target fails? This is the prep PR so that the rehearsal on the openshift/release PR can pass.

**Comment by donpenney** [comment]
@jc-rh It looks like it doesn't like the changes made to recovery/generated/zz_generated.bindata.go in this update. Something different in @sudomakeinstall2 's environment such that the generated code is different?

**Review by jc-rh — APPROVED** [review]

**Comment by jc-rh** [comment]
Overriding [this failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-kni_cluster-group-upgrades-operator/432/pull-ci-openshift-kni-cluster-group-upgrades-operator-main-ci-job/1622813306710396928), as this PR is to get 1.19 specific linter changes in. CI-job will pass again once the CI config and our go.mod are updated to 1.19.

**Pull request merged**
