### PR TITLE
OCPBUGS-4197: Handle error responses from upgrade graph server

### PR DESCRIPTION
**Pull request by jc-rh**

### CODE REVIEW

**Comment by pixelsoccupied** [comment]
Tried on a live cluster too, error is now handled correctly. 

Just for my knowledge (first time reviewing this project's PR) -- we are not expecting any unit test for this fix or `getImageForVersionFromUpdateGraph` in general?

**Comment by jc-rh** [comment]
> Tried on a live cluster too, error is now handled correctly.
> 
> Just for my knowledge (first time reviewing this project's PR) -- we are not expecting any unit test for this fix or `getImageForVersionFromUpdateGraph` in general?

In general, yes. For this function though, it would require mocking an http response. I will see if I can find some examples and add it later.

**Pull request merged**
